name: Export OKX ETH 15m CSV

on:
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run exporter
        run: |
          node -v
          node eth15m-monitor/export_okx_1y.mjs

      - name: Commit CSV (even if warn)
        run: |
          git config user.name "actions-user"
          git config user.email "actions@github"
          git add eth15m-monitor/okx_eth_15m.csv
          git commit -m "update: OKX ETH 15m CSV (1y)" || echo "nothing to commit"
          git push
