name: Export OKX ETH 15m CSV

on:
  workflow_dispatch:

# 防并发互踩：同组的旧运行直接取消
concurrency:
  group: export-okx-eth15m
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0           # 非浅克隆，才能正常 pull/rebase
          persist-credentials: true

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run exporter
        run: |
          node -v
          node export_okx_1y.mjs

      - name: Commit CSV (safe rebase & retry)
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          set -x
          git config user.name  "actions-user"
          git config user.email "actions@github"

          # 只把目标文件加入暂存
          git add eth15m-monitor/okx_eth_15m.csv || true

          # 若没有变化则直接退出
          if git diff --cached --quiet; then
            echo "No CSV changes to commit."
            exit 0
          fi

          git commit -m "update: OKX ETH 15m CSV (1y)" || true

          # 拉取最新远端并 rebase，然后带重试推送，解决“fetch first”
          for i in 1 2 3 4 5; do
            git pull --rebase origin "$BRANCH" || true
            git push origin HEAD:"$BRANCH" && break
            echo "Push failed, retry $i..."
            sleep $((3*i))
          done
