name: Export OKX ETH 15m CSV

on:
  workflow_dispatch: {}
  schedule:
    - cron: "14 1 * * *"   # 每天 09:14 北京时间左右自动运行

concurrency:
  group: export-okx-eth15m
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run exporter
        run: |
          node -v
          node eth15m-monitor/export_okx_1y.mjs

      - name: Commit CSV (safe rebase & retry)
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          set -e
          git config user.name  "actions-user"
          git config user.email "actions@github"
          git add eth15m-monitor/okx_eth_15m.csv || true

          if git diff --cached --quiet; then
            echo "No CSV changes to commit."
            exit 0
          fi

          git commit -m "update: OKX ETH 15m CSV (1y)" || true

          for i in 1 2 3 4; do
            git pull --rebase origin "$BRANCH" || true
            git push origin HEAD:"$BRANCH" && break
            echo "Push failed, retry $i..."
            sleep $((3*i))
          done
