name: Export OKX ETH 15m CSV

on:
  workflow_dispatch:

# 需要写权限用于 push
permissions:
  contents: write

# 并发互斥，防止多个导出互踩
concurrency:
  group: export-okx-eth15m
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # 必须拿到完整 git 历史，才能正常 pull --rebase
          fetch-depth: 0
          persist-credentials: true

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 这里会运行你的导出脚本：export_okx_1y.mjs
      - name: Run exporter
        run: |
          node -v
          node export_okx_1y.mjs

      # 提交 CSV（带 rebase & 重试 & 明确失败）
      - name: Commit CSV (safe rebase & retry)
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          set -x
          git config user.name  "actions-user"
          git config user.email "actions@github"

          # 仅把 CSV 加入暂存；不存在也不报错
          git add eth15m-monitor/okx_eth_15m.csv || true

          # 没有变化就直接正常结束
          if git diff --cached --quiet; then
            echo "No CSV changes to commit."
            exit 0
          fi

          git commit -m "update: OKX ETH 15m CSV (1y)" || true

          ok=0
          for i in 1 2 3 4 5; do
            git pull --rebase origin "$BRANCH" || true
            git push origin HEAD:"$BRANCH" && { ok=1; break; }
            echo "Push failed, retry $i..."
            sleep $((3*i))
          done

          # 5 次仍失败则让任务失败，方便你定位问题
          [ "$ok" = 1 ] || { echo "Push failed after retries"; exit 1; }
