name: Export OKX ETH 15m CSV

on:
  workflow_dispatch: {}   # 手动触发

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # 允许提交文件

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run exporter
        run: node export_okx_15m_to_csv.js

      - name: Commit CSV (if changed)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add okx_eth_15m.csv
          git commit -m "update: OKX ETH/USDT 15m CSV (1y)" || echo "no changes"
          git push
