name: Export OKX ETH 15m CSV

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Start export job"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run exporter (1y, history-candles)
        run: |
          node -v
          node export_okx_1y.mjs

      - name: Commit CSV (even if warn)
        if: ${{ always() }}
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]"
          git add okx_eth_15m.csv
          git commit -m "update: OKX ETH 15m CSV (1y)" || echo "no changes"
          git push
