name: Export OKX ETH 15m CSV

on:
  workflow_dispatch:

concurrency:
  group: export-okx-eth15m
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        # 后面需要 pull --rebase
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run exporter
        shell: bash
        run: |
          node -v
          node export_okx_1y.mjs

      - name: Commit CSV (safe rebase & retry)
        shell: bash
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          set -e
          git config user.name  "actions-user"
          git config user.email "actions@github"

          # 仅把 CSV 加入暂存区（文件在仓库根目录）
          git add okx_eth_15m.csv || true

          # 没有变化就直接结束（避免“空提交”错误）
          if git diff --cached --quiet; then
            echo "No CSV changes to commit."
            exit 0
          fi

          git commit -m "update: OKX ETH 15m CSV (1y)"

          # 安全 push：先 rebase 再 push，失败最多重试 4 次
          for i in 1 2 3 4; do
            git pull --rebase origin "$BRANCH" || true
            git push origin HEAD:"$BRANCH" && break
            echo "Push failed, retry $i..."
            sleep $((3*i))
          done
